[workspace]
members = ["trtx-sys", "trtx", "trtexec-rs"]
resolver = "2"

[workspace.package]
version = "0.8.1+rtx1.6"
edition = "2021"
license = "Apache-2.0"
authors = ["Tarek Ziade", "Markus Tavenrath", "Stephan Seitz"]
repository = "https://github.com/rustnn/trtx-rs"

[workspace.dependencies]
trtx-sys = { path = "trtx-sys" }
trtexec-rs = { path = "trtx" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

# Ignored on crates.io allows to test RustNN with local trtx (so we don't break them accidentally)
[patch.crates-io]
trtx = { path = "trtx" }
trtx-sys = { path = "trtx-sys" }
[patch."https://github.com/rustnn/rustnn/"]
trtx = { path = "trtx" }
trtx-sys = { path = "trtx-sys" }
